name: CD

# Definindo que o workflow deverá rodar após a conclusão de outro workflow.
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    # Condição para executar o comando apenas quando o workflow de gatilho terminar com sucesso.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
